version: "3.9"
services:
  api:
    build: ../../simple_api/
    expose: # only exposed to other containers (services)
      - "9999"
  proxy:
    image: nginx:1.23.2
    depends_on:
            - api
    volumes:
      - ${CFG_PATH}:/etc/nginx/nginx.conf
    ports:
     - "80:80"
    cpus: 2
