#accessLog:
  ##bufferingSize: 1
  ##filePath: "/tmp/access.log"
  #fields:
    #headers:
      #defaultMode: keep
      ##names:
      ##    apikey: keep
accessLog:
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep
entryPoints:
  http:
    address: ':80'
  https:
    address: ':443'
providers:
  file:
    filename: /etc/traefik/traefik-dynamic-cfg.yaml
