version: "3.9"
services:
  api:
    build: ../../simple_api/
    expose: # only exposed to other containers (services)
      - "9999"
  proxy:
    image: haproxytech/haproxy-alpine:latest
    depends_on:
            - api
    volumes:
      - ${CFG_PATH}:/usr/local/etc/haproxy/haproxy.cfg
    ports:
     - "80:80"
    cpus: 2
